CREATE TABLE USER (
    USERNAME VARCHAR(30) PRIMARY KEY,
    UUID VARCHAR(32) UNIQUE,
    PASSWORD VARCHAR(30) NOT NULL,
    LAST_SUCCESSFUL_LOGIN TIMESTAMP
);

CREATE TABLE SHOPPING_LIST (
    ID NUMBER PRIMARY KEY,
    USER_UUID VARCHAR(32),
    NAME VARCHAR(30) NOT NULL,
    ACTIVE BIT DEFAULT 1,
    FOREIGN KEY (USER_UUID) REFERENCES USER(UUID)
);

CREATE TABLE ITEM (
   ID NUMBER PRIMARY KEY,
   NAME VARCHAR(30) UNIQUE
);

CREATE TABLE SHOPPING_LIST_BY_USER (
   ID NUMBER PRIMARY KEY,
   SHOPPING_LIST_ID NUMBER NOT NULL,
   ITEM_ID NUMBER NOT NULL,
   ACTIVE BIT DEFAULT 1,
   FOREIGN KEY (SHOPPING_LIST_ID) REFERENCES SHOPPING_LIST(ID),
   FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID)
);