--liquibase formatted sql
--changeset Nora_Nasz:1 splitStatements:true endDelimiter:;
CREATE TABLE USER (
    USERNAME VARCHAR PRIMARY KEY,
    PASSWORD VARCHAR NOT NULL,
    LAST_SUCCESSFUL_LOGIN TIMESTAMP,
    ROLE VARCHAR NOT NULL
);

CREATE TABLE SHOPPING_LIST_BY_USER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL,
    ACTIVE BIT DEFAULT 1,
    FOREIGN KEY (USER_ID) REFERENCES USER(USERNAME)
);

CREATE TABLE ITEM (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR UNIQUE
);

CREATE TABLE UNIT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR UNIQUE
);

CREATE TABLE SHOPPING_LIST (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    SHOPPING_LIST_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    ITEM_COUNT DOUBLE NOT NULL,
    UNIT_ID INTEGER NOT NULL,
    ACTIVE BIT DEFAULT 1,
    FOREIGN KEY (SHOPPING_LIST_ID) REFERENCES SHOPPING_LIST(ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(ID)
);

--INSERT INTO USER VALUES ('USER', 'PASS', '2012-09-17 18:47:52.69', 'BASIC');
INSERT INTO USER VALUES ('admin', '$2a$10$3TNy.fK.8hgBdt6L/nHYV.eglhCeBA2hIyvpHCdcV8IR3ADSuGL8q', '2012-09-17 18:47:52.69', 'admin');
--INSERT INTO UNIT VALUES (1, 'g');
