--liquibase formatted sql
--changeset Nora_Nasz:1 splitStatements:true endDelimiter:;
CREATE TABLE USER (
    USERNAME VARCHAR(255) PRIMARY KEY,
    PWD VARCHAR(255) NOT NULL,
    LAST_SUCCESSFUL_LOGIN TIMESTAMP,
    ROLES VARCHAR(255) NOT NULL
);

CREATE TABLE SHOPPING_LIST (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USERNAME)
);

CREATE TABLE ITEM_BY_SHOPPING_LIST (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    SHOPPING_LIST_ID INTEGER,
    FOREIGN KEY (SHOPPING_LIST_ID) REFERENCES SHOPPING_LIST(ID)
);


--INSERT INTO USER VALUES ('USER', 'PASS', '2012-09-17 18:47:52.69', 'BASIC');
INSERT INTO USER VALUES ('admin', '$2a$12$nMhPtxgdd50YD.1OKWI8W.Tpv3DfcyfekZ9Vf9Wg6MJIzxBlj7xK2', '2012-09-17 18:47:52.69', 'admin');
--INSERT INTO UNIT VALUES (1, 'g');
